### ISSUE TITLE
Decouple things from common that aren't common

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#7384] opened 2021-11-29 12:54 UTC
And put them in their relevant apps.

**Comment by alexwlchan** [comment] 2021-11-29 15:30
Dupe of https://github.com/wellcomecollection/wellcomecollection.org/issues/6927?

**Comment by alexwlchan** [comment] 2021-12-14 09:50
Closing as dupe.

**Closed by alexwlchan** 2021-12-14 09:50 UTC
