### ISSUE TITLE
Integrate library registration and sign in

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#6336] opened 2021-04-06 16:52 UTC
## Description

Before we can support requesting physical items and access to restricted digitised content, library users need to be able to sign in on wellcomecollection.org. We will support sign in using existing library accounts, as well offer online pre-registration that can be upgraded to a full library account in-person. We will also provide an administration tool for library staff to manage accounts.

## Objective

Researchers engage with a broader range of our collections

## Measures

- Can existing library members can log in to view/manage their account on wc.org?

- Can non-members can set up an account on wc.org?

## Initiatives

- Sign in to an existing account

- Register and verify a new account

- Change password and manage account

- Account administration for library staff

## Done

- UX and technical architecture discovery

**Comment by jennpb** [comment] 2021-04-06 16:52
Link to feature: https://wellcomecollection.productboard.com/feature-board/planning/features/4870169

**Comment by jtweed** [comment] 2021-05-07 16:09
Dupe of https://github.com/wellcomecollection/wellcomecollection.org/issues/6336

**Closed by jtweed** 2021-05-07 16:09 UTC
Labels: :framed_picture: wc.org, ⭐ Key Result

**Comment by jamieparkinson** [comment] 2021-12-02 16:54
@jtweed Do you recall what this is actually a dupe of? It _is_ #6336...

**Comment by jtweed** [comment] 2021-12-10 16:22
That's a good spot. I think I meant #4811.
