### ISSUE TITLE
Physical description data for multi-format video

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5016] opened 2020-01-22 07:59 UTC
**What**
The physical description for videos with multiple formats (DVD and video, for example) is merged into one line, like this:

`1 videocassette (VHS) (1 min.) : 1 DVD (1 min.) : sound, color, PAL. sound, color`

It should be like this:

`1 videocassette (VHS) (1 min.) : sound, color, PAL`
`1 DVD (1 min.) : sound, color`

**Where**
Take a look at Antismoking Baby: https://wellcomecollection.org/works/v6q9dnym

**Comment by jtweed** [comment] 2020-01-23 14:00
Will be fixed by https://github.com/wellcometrust/platform/issues/4201

**Comment by jtweed** [comment] 2020-08-12 12:08
Closing as a dupe of wellcomecollection/platform#4201

**Closed by jtweed** 2020-08-12 12:08 UTC
Labels: catalogue 📚, improvement ✨
