### ISSUE TITLE
Display of contributor role on works pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5943] opened 2021-01-08 16:08 UTC
# Problem to solve
In instances where a `contributor` has multiple roles in the API, we render the two roles with the punctuation from the API and with a hyphen to separate. This results in some ugliness in the contributor tag:

<img width="547" alt="Screenshot 2021-01-08 at 15 43 45" src="https://user-images.githubusercontent.com/1446139/104034147-6bdeba80-51c8-11eb-844f-06e1f5dd9ee5.png">
https://wellcomecollection.org/works/apfaky8h

`roles: [
{
label: "author,",
type: "ContributionRole"
},
{
label: "publisher.",
type: "ContributionRole"
}
],`

In instances where a contributor has multiple `ContributionRole`s, these should display as a comma-separated list, like this:
<img width="408" alt="Screenshot 2021-01-08 at 16 01 49" src="https://user-images.githubusercontent.com/1446139/104036163-fd4f2c00-51ca-11eb-885d-d3e67ac15ce0.png">

## Questions
- Is it better do handle this on the client or in the data? 

Options:
- ~~Strip punctuation from `ContributorRole` in API~~
- ~~Handle on client-side by stripping full-stop, retaining any commas from `ContributorRole` and deleting the separating hyphen~~
- [Per @jtweed's suggestion] Rely on the fact that the roles in the API are ordered and concatenate without adding additional punctuation, ie render what is there as it will display correctly and match what C&R expect based on what’s in Sierra.

In this case, it should look like this:
<img width="417" alt="Screenshot 2021-01-11 at 09 54 48" src="https://user-images.githubusercontent.com/1446139/104166717-1f2af780-53f3-11eb-9c3e-db990a01e550.png">

[Link to example](https://wellcomecollection.org/works/apfaky8h)

**Comment by jtweed** [comment] 2021-01-09 12:11
I don’t think we’re anywhere near being able to reliably strip punctuation from MARC data without losing meaning, so I’d vote for a third option:

- Rely on the fact that the roles in the API are ordered and concatenate without adding additional punctuation, ie render what is there as it will display correctly.

**Comment by jamesgorrie** [comment] 2021-01-13 15:45
Is this a dupe of [this closed issue](https://github.com/wellcomecollection/wellcomecollection.org/issues/5758)

**Comment by jtweed** [comment] 2021-01-13 16:11
It's a bug fix on how we display multiple contributor roles on the same contributor.

**Closed** 2021-02-24 19:25 UTC
Labels: Project: collections access, catalogue 📚, improvement ✨
