### ISSUE TITLE
Enable online requesting for manual requests

### ISSUE THREAD

**Issue by jtweed** [wellcomecollection/wellcomecollection.org#9700] opened 2023-04-28 10:20 UTC
# Background

<p></p>

# Problems to solve

We have multiple offsite storage facilities for materials from the collections, including bound journals, artworks, MOH reports\. Over time, more will be added as the collections grow\.

<p></p>

We have other materials that are uncatalogued \(but onsite\) and\/or unitemised \(on\/offsite\) that rely on manual requests to gather the pertinent information from users\.

<p></p>

Users must use a physical triplicate form to make a manual request\. They either do this for themselves when in the library, or get in touch with the Library Enquiries team to fill out the request for them\.

<p></p>

- The current process of getting materials back onsite for users and staff is cumbersome and inefficient​\. Users don't know what to expect in terms of delivery and pickup\.

  <p></p>

# Future

We want to improve the end\-to\-end procedure, including allowing readers to request offsite, unitemised, and uncatalogued materials directly from the website

<p></p>

An online requesting process that <span data-preserve-white-space></span>

- Generates a printed slip for the retrievals team

- Gives user a timeframe for delivery at some point in the future

- Helps library teams to retrieve and store materials efficiently

  <p></p>

**Comment by jennpb** [comment] 2023-08-14 13:53
Current quarter: Share knowledge and create staging environment for Collections teams to make manual requests available to request online​

**Comment by kenoir** [comment] 2024-06-11 08:59
Closing as dupe of https://github.com/wellcomecollection/catalogue-api/issues/784

**Closed by kenoir** 2024-06-11 08:59 UTC
Labels: 💡Initiative
